import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Landing.module.css'
import LayoutDefault from '../layout/default'
import phone from '../public/images/png-phone (1).png'
import {Col,Row} from 'reactstrap'


export default function Landing() {

  // const token = localStorage.getItem('token')
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LayoutDefault>
        <div>
          <div className={styles.jbt}>
              <Row className={styles.landing}>
                <Col className=" d-flex flex-column justify-content-center">
                  <h1 className={styles.ket}>
                    Awesome App
                    For Saving Time.
                  </h1>
                  <div className={styles.ket2}>
                    We bring you a mobile app for banking problems that
                    oftenly wasting much of your times.
                  </div>
                  <div>
                  <button className={styles.try}> Try It Free </button>
                  </div>
             
                </Col>
                <Col className="d-flex justify-content-end">
                  <Image className="ms-5" src={phone} alt="" />
                </Col>
              </Row>
          </div>
          {/* <div className={styles.iklan}>
            <Row>
                <Col>1</Col>
                <Col>2</Col>
            </Row>
          </div> */}
        </div>
      </LayoutDefault>
    </div>
  )
}
