import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Landing.module.css'
import LayoutDefault from '../layout/default'
import phone from '../public/images/png-phone (1).png'
import {Col,Row} from 'reactstrap'
import windows from '../public/images/windows.svg'
import dropbox from '../public/images/dropbox.svg'
import bnb from '../public/images/bnb.svg'
import hm from '../public/images/hm.svg'
import phone2 from '../public/images/phone.svg'
import gmbk from '../public/images/gmbk.svg'
import download from '../public/images/download.svg'
import phoneGreat from '../public/images/phoneGreat.svg'
import AOS from "aos";
import "aos/dist/aos.css";
import { useEffect } from "react";



export default function Landing() {

  useEffect(() => {
    AOS.init({
      duration : 2000
    });
    AOS.refresh();
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LayoutDefault>
        <div>
          <div className={styles.jbt}>
              <Row className={styles.landing}>
                <Col className=" d-flex flex-column justify-content-center">
                  <h1 className={styles.ket}>
                    Awesome App
                    For Saving Time.
                  </h1>
                  <div className={styles.ket2}>
                    We bring you a mobile app for banking problems that
                    oftenly wasting much of your times.
                  </div>
                  <div>
                  <button className={styles.try}> Try It Free </button>
                  </div>
             
                </Col>
                <Col className={styles.gmbrJmb}>
                  <Image className="ms-5" src={phone} alt="" />
                </Col>
              </Row>
          </div>
          <div className={styles.iklan}>
            <Row data-aos="fade-up" className="w-75 justify-content-center align-items-center">
                <Col><Image src={windows} alt ="" /></Col>
                <Col><Image src={dropbox} alt ="" /></Col>
                <Col><Image src={hm} alt ="" /></Col>
                <Col><Image src={bnb} alt ="" /></Col>               
            </Row>
          </div>
          <div className={styles.about}>
              <Row className="w-75 justify-content-center align-items-center">
                <Col lg="12" data-aos="fade-up" className={styles.titleAbout}> <b className={styles.ba}>About</b> the Application.</Col>
                <Col lg="7" data-aos="zoom-in-up" className={styles.ketA}> We have some great features from the application and it’s totally free to use by all users around the world. </Col>           
                <Col lg="12">
                  <Row  data-aos-easing="linear" data-aos-duration="1500" className="w-100 mt-5 justify-content-center align-items-center">
                    <Col data-aos="fade-right" lg="3" className={styles.cardA}>
                        <div className="mb-3"><Image src={phone2} alt=""/></div>
                        <div className="mb-3"><b>Data Privacy</b></div>
                        <div className={styles.ketCard}>We have 24/7 contact support so you can contact us whenever you want and we will respond it.</div>
                    </Col>
                    <Col data-aos="zoom-in-up" lg="3" className={styles.cardA}>
                        <div className="mb-3"><Image src={gmbk} alt=""/></div>
                        <div className="mb-3"><b>24/7 Support</b></div>
                        <div className={styles.ketCard}>We make sure your data is safe in our database and we will encrypt any data you submitted to us.</div>
                    </Col>
                    <Col data-aos="fade-left" lg="3" className={styles.cardA}>
                        <div className="mb-3"><Image src={download} alt=""/></div>
                        <div className="mb-3"><b>Easy Download</b></div>
                        <div className={styles.ketCard}>Zwallet is 100% totally free to use it’s now available on Google Play Store and App Store.</div>
                    </Col>               
                  </Row>
                </Col>              
              </Row>
          </div>
          <div className={styles.great}>
            <Row className="w-75 justify-content-center align-items-center">
              <Col className={styles.gmbr}data-aos="fade-down" data-aos-duration="4500"><Image className={styles.phoneG} src={phoneGreat} alt="" /></Col>
              <Col>
                  <div  data-aos="fade-left" className={styles.titleGreat}>All The <b className={styles.ba}>Great</b> Zwallet Features.</div>
                  <div data-aos="fade-right" className={styles.CardGreat}>
                    <div className="d-flex w-100">
                      <div>1.</div>
                      <b className="ms-2"> Small Fee</b>
                    </div>
                    <div className={styles.ketCardGreat}>We only charge 5% of every success transaction done in Zwallet app.</div>
                  </div>
                  <div data-aos="fade-right" data-aos-duration="1500" className={styles.CardGreat}>
                    <div className="d-flex w-100">
                      <div>2.</div>
                      <b className="ms-2"> Data Secured</b>
                    </div>
                    <div className={styles.ketCardGreat}>All your data is secured properly in our system and it’s encrypted.</div>
                  </div>
                  <div data-aos="fade-right" data-aos-duration="1000" className={styles.CardGreat}>
                    <div className="d-flex w-100">
                      <div>3.</div>
                      <b className="ms-2"> User Friendly</b>
                    </div>
                    <div className={styles.ketCardGreat}>Zwallet come up with modern and sleek design and not complicated.</div>
                  </div>
              </Col>
            </Row>            
          </div>
        </div>
      </LayoutDefault>
    </div>
  )
}
